
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.Table tableMain;
	private global::Gtk.Button buttonConvert;
	private global::Gtk.Button buttonOpenFile;
	private global::Gtk.Button buttonSaveFile;
	private global::Gtk.Entry entryOpenFile;
	private global::Gtk.Entry entrySaveFile;
	private global::Gtk.Label labelOpenFile;
	private global::Gtk.Label labelSaveFile;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.tableMain = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
		this.tableMain.Name = "tableMain";
		this.tableMain.RowSpacing = ((uint)(6));
		this.tableMain.ColumnSpacing = ((uint)(6));
		// Container child tableMain.Gtk.Table+TableChild
		this.buttonConvert = new global::Gtk.Button ();
		this.buttonConvert.CanFocus = true;
		this.buttonConvert.Name = "buttonConvert";
		this.buttonConvert.UseUnderline = true;
		this.buttonConvert.Label = global::Mono.Unix.Catalog.GetString ("Convert");
		this.tableMain.Add (this.buttonConvert);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.tableMain [this.buttonConvert]));
		w1.TopAttach = ((uint)(2));
		w1.BottomAttach = ((uint)(3));
		w1.LeftAttach = ((uint)(2));
		w1.RightAttach = ((uint)(3));
		w1.XOptions = ((global::Gtk.AttachOptions)(4));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableMain.Gtk.Table+TableChild
		this.buttonOpenFile = new global::Gtk.Button ();
		this.buttonOpenFile.CanFocus = true;
		this.buttonOpenFile.Name = "buttonOpenFile";
		this.buttonOpenFile.UseUnderline = true;
		this.buttonOpenFile.Label = global::Mono.Unix.Catalog.GetString ("Chose...");
		this.tableMain.Add (this.buttonOpenFile);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.tableMain [this.buttonOpenFile]));
		w2.LeftAttach = ((uint)(2));
		w2.RightAttach = ((uint)(3));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableMain.Gtk.Table+TableChild
		this.buttonSaveFile = new global::Gtk.Button ();
		this.buttonSaveFile.CanFocus = true;
		this.buttonSaveFile.Name = "buttonSaveFile";
		this.buttonSaveFile.UseUnderline = true;
		this.buttonSaveFile.Label = global::Mono.Unix.Catalog.GetString ("Chose...");
		this.tableMain.Add (this.buttonSaveFile);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.tableMain [this.buttonSaveFile]));
		w3.TopAttach = ((uint)(1));
		w3.BottomAttach = ((uint)(2));
		w3.LeftAttach = ((uint)(2));
		w3.RightAttach = ((uint)(3));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableMain.Gtk.Table+TableChild
		this.entryOpenFile = new global::Gtk.Entry ();
		this.entryOpenFile.CanFocus = true;
		this.entryOpenFile.Name = "entryOpenFile";
		this.entryOpenFile.IsEditable = true;
		this.entryOpenFile.InvisibleChar = '●';
		this.tableMain.Add (this.entryOpenFile);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.tableMain [this.entryOpenFile]));
		w4.LeftAttach = ((uint)(1));
		w4.RightAttach = ((uint)(2));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableMain.Gtk.Table+TableChild
		this.entrySaveFile = new global::Gtk.Entry ();
		this.entrySaveFile.CanFocus = true;
		this.entrySaveFile.Name = "entrySaveFile";
		this.entrySaveFile.IsEditable = true;
		this.entrySaveFile.InvisibleChar = '●';
		this.tableMain.Add (this.entrySaveFile);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.tableMain [this.entrySaveFile]));
		w5.TopAttach = ((uint)(1));
		w5.BottomAttach = ((uint)(2));
		w5.LeftAttach = ((uint)(1));
		w5.RightAttach = ((uint)(2));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableMain.Gtk.Table+TableChild
		this.labelOpenFile = new global::Gtk.Label ();
		this.labelOpenFile.Name = "labelOpenFile";
		this.labelOpenFile.LabelProp = global::Mono.Unix.Catalog.GetString ("HSBC File");
		this.tableMain.Add (this.labelOpenFile);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.tableMain [this.labelOpenFile]));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tableMain.Gtk.Table+TableChild
		this.labelSaveFile = new global::Gtk.Label ();
		this.labelSaveFile.Name = "labelSaveFile";
		this.labelSaveFile.LabelProp = global::Mono.Unix.Catalog.GetString ("FreeAgent File");
		this.tableMain.Add (this.labelSaveFile);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.tableMain [this.labelSaveFile]));
		w7.TopAttach = ((uint)(1));
		w7.BottomAttach = ((uint)(2));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox1.Add (this.tableMain);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.tableMain]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 428;
		this.DefaultHeight = 130;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
